name: deploy to remote

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: next
    steps:
      - uses: actions/checkout@v1
      - run: npm install && npm run lint && npm run build
      - name: ssh key generate
        run: echo "$SSH_PRIVATE_KEY" > key && chmod 600 key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: rsync deploy
        run: rsync -auzrv -e "ssh -i key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 10022" --delete ./out/* xs150334@sv10235.xserver.jp:/home/xs150334/magicgifted.com/public_html/stg-tsumiage.magicgifted.com/ --exclude .htaccess
